# Generated by Django 5.0.7 on 2024-07-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status_client', models.CharField(choices=[('Action requise', 'Action requise'), ('Attendre', 'Attendre'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé'), ('Confirmé', 'Confirme'), ('En attente', 'En attente'), ('Waiting Approval', 'Waiting Approval')], default='En attente', max_length=20)),
                ('status_supplier', models.CharField(choices=[('Action requise', 'Action requise'), ('Attendre', 'Attendre'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé'), ('Confirmé', 'Confirme'), ('En attente', 'En attente'), ('Waiting Approval', 'Waiting Approval')], default='Action requise', max_length=20)),
                ('type_prestation', models.CharField(blank=True, max_length=35, null=True)),
                ('charge_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('refund_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('charge_capture', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_offer', to='prestations.client')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_offer', to='prestations.supplier')),
            ],
        ),
    ]
